"""add last_login column to users table

Revision ID: cbc4d31f7dbf
Revises: 7a1b2c3d4e5f
Create Date: 2026-02-03 02:05:48.425625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc4d31f7dbf'
down_revision: Union[str, Sequence[str], None] = '7a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agentresponse')
    op.drop_table('task')
    op.drop_table('toolcall')
    op.drop_table('conversations')
    op.drop_table('user')
    op.drop_table('messages')
    op.drop_index('ix_conversation_conversation_id', table_name='conversation')
    op.drop_index('ix_conversation_user_id', table_name='conversation')
    op.drop_table('conversation')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('todos')
    op.drop_index('ix_message_conversation_id', table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=9), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('message_metadata', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_conversation_id', 'message', ['conversation_id'], unique=False)
    op.create_table('todos',
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=6), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('conversation',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_user_id', 'conversation', ['user_id'], unique=False)
    op.create_index('ix_conversation_conversation_id', 'conversation', ['conversation_id'], unique=1)
    op.create_table('messages',
    sa.Column('role', sa.VARCHAR(length=9), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=13), nullable=False),
    sa.Column('tool_calls', sa.VARCHAR(), nullable=True),
    sa.Column('tool_responses', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('conversation_id', sa.CHAR(length=32), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conversations',
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('openai_thread_id', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toolcall',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('message_id', sa.CHAR(length=32), nullable=False),
    sa.Column('tool_name', sa.VARCHAR(), nullable=False),
    sa.Column('tool_input', sa.VARCHAR(), nullable=False),
    sa.Column('result', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agentresponse',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('message_id', sa.CHAR(length=32), nullable=False),
    sa.Column('content_segments', sa.VARCHAR(), nullable=False),
    sa.Column('finish_reason', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
